# This file defines the configuration structure.
# Secret values should be provided via environment variables
# (e.g., AUTH_LOGIN_PASSWORD) or a local config.local.yaml file.

llm:
  provider: "openai"

openai:
  api_key: ""
  model: "gpt-4o-mini"
  max_tokens: 1000
  timeout: 30

tts:
  enabled: false

sst:
  enabled: false

auth:
  session_secret: ""
  login_password: ""